name: Linux CI

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.ipynb'
      - 'myst.yml'
  # Enables manual triggering from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.name }} ${{ matrix.build_type }}
    # Redirects all jobs to Blacksmith infrastructure
    runs-on: blacksmith-4vcpu-ubuntu-2204
    container:
      image: borglab/gtsam-ci:${{ matrix.os }}-${{ matrix.compiler }}-${{ matrix.version }}
      env:
        CMAKE_BUILD_TYPE: ${{ matrix.build_type }}
        GTSAM_BUILD_UNSTABLE: ${{ matrix.build_unstable }}
      volumes:
        - ${{ github.workspace }}:/gtsam
    strategy:
      fail-fast: true
      matrix:
        # Use only one source of truth for the matrix to avoid mismatched keys
        build_type: [Debug, Release]
        build_unstable: [ON]
        include:
          - name: ubuntu-22.04-gcc-11
            os: ubuntu-22.04
            compiler: gcc
            version: "11"

          - name: ubuntu-22.04-clang-11
            os: ubuntu-22.04
            compiler: clang
            version: "11"

          - name: ubuntu-24.04-gcc-14
            os: ubuntu-24.04
            compiler: gcc
            version: "14"

          - name: ubuntu-24.04-clang-16
            os: ubuntu-24.04
            compiler: clang
            version: "16"

          - name: ubuntu-24.04-clang-16-boost
            os: ubuntu-24.04
            compiler: clang
            version: "16"

        exclude:
          - name: ubuntu-24.04-clang-16-boost
            build_type: Debug

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Boost Environment (Conditional)
        if : contains(matrix.name, 'boost') && matrix.build_type == 'Release'
        run: |
          echo "GTSAM_USE_BOOST_FEATURES=ON" >> $GITHUB_ENV
          echo "GTSAM_ENABLE_BOOST_SERIALIZATION=ON" >> $GITHUB_ENV
          echo "Using Boost features."
      
      - name: Set GeographicLib Environment (Conditional)
        if: contains(matrix.name, 'geographiclib') && matrix.build_type == 'Release'
        run: |
          echo "GTSAM_ENABLE_GEOGRAPHICLIB=ON" >> $GITHUB_ENV

      - name: Build and Test
        run: |
          # Ensure workspace permissions for the container
          git config --global --add safe.directory /gtsam
          .github/scripts/unix.sh -t
